version: 0.2

phases:
  build:
    commands:
      -echo entered the build phase...
      -mvn clean package
  post_build:
    commands:
      -echo Bild completed successfully
artifacts:
  files:
    - target/ubs-service.jar
  discard-paths: yes